name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '24.0.0+36'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests with Maven
        run: mvn test